namespace VisualArchitect.Api.Orchestration.Abstractions.Mediator;

/// <summary>
/// Service sends <see cref="IRequest"/>/<see cref="IRequest{TResponse}"/> through the request pipeline.
/// </summary>
public interface IRequestSender
{
    /// <summary>
    /// Sends the given <paramref name="request"/> through the messaging pipeline.
    /// </summary>
    /// <typeparam name="TRequest">Type of request being sent.</typeparam>
    /// <typeparam name="TResponse">Type of response expected.</typeparam>
    /// <param name="request">Request being sent.</param>
    /// <param name="cancellationToken">Cancellation token for aborting asynchronous operations.</param>
    /// <returns>The response generated by the request handler or middleware.</returns>
    Task<TResponse> SendAsync<TRequest, TResponse>(TRequest request, CancellationToken cancellationToken = default) where TRequest : IRequest<TResponse>;

    /// <summary>
    /// Sends the given <paramref name="request"/> through the messaging pipeline.
    /// </summary>
    /// <typeparam name="TRequest">Type of request being sent.</typeparam>
    /// <param name="request">Request being sent.</param>
    /// <param name="cancellationToken">Cancellation token for aborting asynchronous operations.</param>
    Task SendAsync<TRequest>(TRequest request, CancellationToken cancellationToken = default) where TRequest : IRequest;
}
